name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:        
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build
      env:
        CI: true
        
    - name: Deploy to GitHub Pages
      run: |
        echo "${{ secrets.GITHUB_DEPLOY_KEY }}" > ~/.ssh/github_actions
        chmod 600 ~/.ssh/github_actions
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/github_actions
        ./deploy_to_github_pages.sh 'dist' "git@github.com:${{ github.repository }}.git" 'gh-pages' 'GitHub Actions'
        
    