name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:        
    - uses: actions/checkout@v2
    - name: Prepare GitHub Actions Deploy Key
      run: |
        mkdir -p ~/.ssh
        cat ~/.ssh/github_actions <<< "${GITHUB_DEPLOY_KEY}"
        chmod 600 ~/.ssh/github_actions
      env:
        GITHUB_DEPLOY_KEY: "${{ secrets.GITHUB_DEPLOY_KEY }}"
        
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build
      env:
        CI: true
        
    - name: Deploy to GitHub Pages
      run: |
        eval $(ssh-agent -s) >/dev/null
        ssh-add ~/.ssh/github_actions
        ./deploy_to_github_pages.sh 'dist' "git@github.com:${{ github.repository }}.git" 'gh-pages' 'GitHub Actions'
        
    